
class AppString{
  // App Strings
static String getUri = "https://fluttersddev.000webhostapp.com/api/";
static String appName = "اورنج فروتس";
static String orderInfo = "بيانات الطلب الأساسية";
static String orderNumber = "رقم الطلب";
static String orderHistory = "تاريخ الطلب";
static String amount = "الكمية";
static String count = "العدد";
static String totlePrice = "اجمالي السعر";
static String products = "المنتجات";
static String compliteOrder = "أكمال الطلب";
static String name = "الاسم";
static String phone = "رقم الهاتف";
static String password = "كلمة المرور";
static String login = "تسجيل دخول";
static String newAccount = "تسجيل جديد";
static String or = "او";
static String restorePassword = "استعادة كملة المرور";
static String sccessSendCode = "تم ارسال كلمة مرور جديدة في رقم الهاتف";////////////////
static String done = "موافق";
static String weSendCodeToPhone = "أرسلنا رمز التأكيد الى رقم الهاتف";
static String checkLogin = "تأكيد التسجيل";/////////////
static String reSendCode = "إعادة ارسال الرمز";
static String sccessCodePin = "تم ادخال الكود بنجاح";/////////////////
static String continu = "إستمرار";/////////////////
static String selectYourLocation = "حدد مكانك علي الخريطة";
static String where_you_want_to_get_your_order = "اين تود اسلام طلبك";/////////////
static String cart = "السلة";
static String delivery = "التوصيل";
static String payment = "الدفع";
static String addLocation = "اضف عنوان";
static String appTitle = "المحافظة";
static String city = "المدينة";
//static String appTitle = "الحي";
static String roud = "الشارع";///////////////////
static String honeDescription = "وصف المنزل";
static String address = "العناوين";
static String deliveryLocation = "مكان التوصيل";
static String time = "الوقت";
static String addComment = "اضف ملاحظة";////////////
static String paymentType = "وسيلة الدفع";
static String cash = "كاش";
static String visa = "فيزا كارد + ماستر";
static String mdaa = "مدي";
static String bank = "تحويل بنكي";
static String userAccount = "صاحب الحساب";////////////////
static String enterCardNumber = "ادخل رقم البطاقة";
static String month = "الشهر";//////////////
static String year = "السنة";
static String cardPass = "الرقم السري";
static String cartDetails = "ملخصة السلة";
static String orderPrice = "تكلفة التوصيل";
static String orderFee = "ضريبة القيمة المضافة";
static String you_have_cobone = "هل لديك كوبون تخفيض";
static String apply = "تطبيق";
//static String appTitle = "الموافقه على  سياسة الخصوية";
static String deliveryTime = "موعد التوصيل";
//static String appTitle = "تم الدفع بنجاح";
static String aboutApp = "عن التطبيق";
static String profile = "البيانات الشخصية";
static String lang = "اللغة";/////////////////////
static String arabic = "العربية";
static String changeProfile = "تعديل الملف الشخصي";
static String orders = "الطلبات";
//static String appTitle = "للشكاوي والتعليقات";
//static String appTitle = "الطلبات الحالية";
//static String appTitle = "الطلبات المنتهية";
static String state = "الحالة";
//static String appTitle = "اكتمل الطلب";
static String totleOrder = "اجمالي الطلب";
//static String appTitle = "رجوع";
static String orderState = "حالة الطلب";
static String sended = " تم الارسال";
//static String appTitle = "تم ارسال الطلب";
//static String appTitle = "تم ارسال طلبك سيتم التواصل معك وارسال الطلبية في الموقع المحدد في التطبيق";
//static String appTitle = "المندوب في الطريق";
//static String appTitle = "مندوبنا في الطريق اليك الرجاء متابعة الطلب وتقييم الطلب وتقييم المندوب";
//static String appTitle = "تم تسليم الطلبية";
//static String appTitle = "قام مندوبنا بتسليم الطلبية في الموقع المحدد وفي الزمن المحدد لانهاء الطلب اضغط انهاء";
//static String appTitle = "ملاحظات المندوب";
//static String appTitle = "قبل ";
//static String appTitle = "انهاء الطلب";
//static String appTitle = "لايتم تقعيل انهاء الطلب الا بعد تسليم الطلبية";
//static String appTitle = "تقييم المندوب";
static String rating = "تقييم";

}